const http=require('http');const {URL}=require('url');const {pool}=require('./db');const {loadM3U}=require('./connectors/m3u');const stalker=require('./lib/stalker');const {parseXmltv}=require('./lib/xmltv');
const PORT=Number(process.env.PORT||8080);const json=(res,s,d)=>{res.statusCode=s;res.setHeader('Content-Type','application/json');res.setHeader('Access-Control-Allow-Origin','*');res.end(JSON.stringify(d));};
const read=async req=>{let x='';for await(const c of req)x+=c;return x?JSON.parse(x):{};};const route=(m,p)=>m+' '+p;
async function sourceById(id){const q=await pool.query('select * from sources where id=$1',[id]);if(!q.rows[0])throw new Error('source_not_found');return q.rows[0];}
const server=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.statusCode=204;res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.end();return;}const u=new URL(req.url,`http://${req.headers.host}`);const key=route(req.method,u.pathname);
if(key==='GET /health')return json(res,200,{ok:true,service:'nova-api',version:'2.0.0'});
if(key==='GET /api/v1')return json(res,200,{name:'NOVA TV API',version:'2.0.0',sources:['m3u','stalker']});
if(key==='GET /api/v1/sources'){const q=await pool.query('select id,type,name,config,created_at,updated_at from sources order by created_at desc');return json(res,200,{sources:q.rows});}
if(key==='POST /api/v1/sources'){const b=await read(req);if(!b.type||!b.name||!b.config)return json(res,400,{error:'type_name_config_required'});const p=await pool.query('select id from profiles order by created_at limit 1');const q=await pool.query('insert into sources(profile_id,type,name,config) values($1,$2,$3,$4) returning id,type,name,created_at',[p.rows[0].id,b.type,b.name,b.config]);return json(res,201,{source:q.rows[0]});}
if(key==='POST /api/v1/m3u/parse'){const b=await read(req);if(!b.url)return json(res,400,{error:'url_required'});return json(res,200,{items:await loadM3U(b.url)});}
if(key==='POST /api/v1/m3u/import'){const b=await read(req);if(!b.sourceId||!b.url)return json(res,400,{error:'sourceId_and_url_required'});const items=await loadM3U(b.url);const c=await pool.connect();try{await c.query('begin');await c.query('delete from channels where source_id=$1',[b.sourceId]);await c.query('delete from movies where source_id=$1',[b.sourceId]);for(const x of items){const isMovie=x.kind==='movie'||/\.(mp4|mkv|mov)(\?|$)/i.test(x.url);if(isMovie)await c.query('insert into movies(source_id,external_id,title,poster_url,stream_url) values($1,$2,$3,$4,$5)',[b.sourceId,x.tvgId,x.title,x.logo,x.url]);else await c.query('insert into channels(source_id,external_id,name,group_name,logo_url,stream_url,epg_id) values($1,$2,$3,$4,$5,$6,$7)',[b.sourceId,x.tvgId,x.title,x.group,x.logo,x.url,x.tvgId]);}await c.query('update sources set updated_at=now() where id=$1',[b.sourceId]);await c.query('commit');return json(res,200,{imported:items.length});}catch(e){await c.query('rollback');throw e}finally{c.release();}}
if(key==='POST /api/v1/epg/import'){const b=await read(req);if(!b.sourceId||!b.url)return json(res,400,{error:'sourceId_and_url_required'});const xml=await (await fetch(b.url)).text();const items=parseXmltv(xml);const c=await pool.connect();try{await c.query('begin');await c.query('delete from epg_programs where source_id=$1',[b.sourceId]);for(const x of items)await c.query('insert into epg_programs(source_id,channel_epg_id,title,description,start_at,end_at,category) values($1,$2,$3,$4,$5,$6,$7)',[b.sourceId,x.channelId,x.title,x.description,x.startAt,x.endAt,x.category]);await c.query('commit');return json(res,200,{imported:items.length});}catch(e){await c.query('rollback');throw e}finally{c.release();}}
if(key==='GET /api/v1/library'){const [c,m,s,e]=await Promise.all([pool.query('select id,name,group_name,logo_url,stream_url,epg_id from channels order by group_name,name'),pool.query('select id,title,poster_url,backdrop_url,stream_url,year,overview from movies order by title'),pool.query('select id,title,poster_url,backdrop_url from series order by title'),pool.query('select channel_epg_id,title,description,start_at,end_at,category from epg_programs where end_at>now() order by start_at limit 500')]);return json(res,200,{channels:c.rows,movies:m.rows,series:s.rows,epg:e.rows});}
if(key==='POST /api/v1/stalker/handshake'){const b=await read(req);return json(res,200,await stalker.handshake(b));}
if(key==='POST /api/v1/stalker/profile'){const b=await read(req);return json(res,200,await stalker.profile(b));}
if(key==='POST /api/v1/stalker/categories'){const b=await read(req);return json(res,200,await stalker.categories(b));}
if(key==='POST /api/v1/stalker/channels'){const b=await read(req);return json(res,200,await stalker.channels(b));}
if(key==='POST /api/v1/stalker/vod'){const b=await read(req);return json(res,200,await stalker.vod(b));}
if(key==='POST /api/v1/stalker/series'){const b=await read(req);return json(res,200,await stalker.series(b));}
if(key==='POST /api/v1/stalker/link'){const b=await read(req);return json(res,200,await stalker.createLink(b));}
if(key==='GET /api/v1/progress'){const profileId=u.searchParams.get('profileId');const q=await pool.query('select * from watch_progress where profile_id=$1 order by updated_at desc',[profileId]);return json(res,200,{items:q.rows});}
if(key==='PUT /api/v1/progress'){const b=await read(req);await pool.query('insert into watch_progress(profile_id,content_type,content_id,position_seconds,duration_seconds,updated_at) values($1,$2,$3,$4,$5,now()) on conflict(profile_id,content_type,content_id) do update set position_seconds=excluded.position_seconds,duration_seconds=excluded.duration_seconds,updated_at=now()',[b.profileId,b.contentType,b.contentId,b.positionSeconds||0,b.durationSeconds||0]);return json(res,200,{ok:true});}
if(key==='GET /api/v1/favorites'){const profileId=u.searchParams.get('profileId');const q=await pool.query('select * from favorites where profile_id=$1 order by created_at desc',[profileId]);return json(res,200,{items:q.rows});}
if(key==='POST /api/v1/favorites'){const b=await read(req);await pool.query('insert into favorites(profile_id,content_type,content_id) values($1,$2,$3) on conflict do nothing',[b.profileId,b.contentType,b.contentId]);return json(res,201,{ok:true});}
if(key==='DELETE /api/v1/favorites'){const b=await read(req);await pool.query('delete from favorites where profile_id=$1 and content_type=$2 and content_id=$3',[b.profileId,b.contentType,b.contentId]);return json(res,200,{ok:true});}
return json(res,404,{error:'not_found'});}catch(e){console.error(e);return json(res,500,{error:e.message||'server_error'});}});
server.listen(PORT,'0.0.0.0',()=>console.log(`NOVA API listening on ${PORT}`));
